///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DoctorModelDoctorsImage {
/*
{
  "url": "https://images.unsplash.com/photo-1545254644-a60835b8d36e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=749&q=80"
} 
*/

  String? url;

  DoctorModelDoctorsImage({
    this.url,
  });
  DoctorModelDoctorsImage.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    return data;
  }
}
class DoctorModelDoctors {
  String? id;
  String? fullName;
  String? userStatus;
  String? gender;
  DoctorModelDoctorsImage? image;

  DoctorModelDoctors({
    this.id,
    this.fullName,
    this.userStatus,
    this.gender,
    this.image,
  });

  DoctorModelDoctors.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    fullName = json['full_name']?.toString();
    userStatus = json['user_status']?.toString();
    gender = json['gender']?.toString();
    image = (json['image'] != null) ? DoctorModelDoctorsImage.fromJson(json['image']) : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['full_name'] = fullName;
    data['user_status'] = userStatus;
    data['gender'] = gender;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    return data;
  }

  toList() {}
}


class DoctorModel {
/*
{
  "doctors": [
    {
      "full_name": "Turgay Buglu",
      "user_status": "premium",
      "gender": "male",
      "image": {
        "url": "https://images.unsplash.com/photo-1545254644-a60835b8d36e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=749&q=80"
      }
    }
  ]
} 
*/

  List<DoctorModelDoctors?>? doctors;

  DoctorModel({
    this.doctors,
  });
  DoctorModel.fromJson(Map<String, dynamic> json) {
  if (json['doctors'] != null) {
  final v = json['doctors'];
  final arr0 = <DoctorModelDoctors>[];
  v.forEach((v) {
  arr0.add(DoctorModelDoctors.fromJson(v));
  });
    doctors = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (doctors != null) {
      final v = doctors;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['doctors'] = arr0;
    }
    return data;
  }
}